Repository g-truc/glm, pull requests merged in 2020-11, with the labels that each got.

#1040 Adding constexpr qualifiers for dot and cross product
  glm/detail/func_geometric.inl
  glm/geometric.hpp
Labels: core, enhancement

#1038 fix: glm::angle() discards the sign of result for angles in range (2*pi-1, 2*pi)
  glm/ext/quaternion_trigonometric.inl
  test/ext/ext_quaternion_trigonometric.cpp
Labels: bug

#1044 Build appveyor C.I. only on master branch
  .appveyor.yml
Labels: enhancement, test
