Repository g-truc/glm, pull requests merged in 2022-10, with the labels that each got.

#1114 cleanup doxygen and codespell
  glm/ext/matrix_clip_space.hpp
  glm/ext/matrix_float3x2.hpp
  glm/ext/matrix_uint2x3.hpp
  glm/ext/matrix_uint2x4_sized.hpp
  glm/ext/matrix_uint3x2.hpp
  glm/ext/quaternion_geometric.hpp
  glm/ext/scalar_relational.hpp
  glm/ext/scalar_ulp.hpp
  glm/ext/vector_reciprocal.hpp
  glm/ext/vector_ulp.hpp
  glm/glm.hpp
  glm/gtc/integer.hpp
  glm/gtc/matrix_inverse.hpp
  glm/gtc/random.hpp
  glm/gtc/ulp.hpp
  glm/gtx/associated_min_max.hpp
  glm/gtx/easing.hpp
  glm/gtx/extended_min_max.hpp
  glm/gtx/handed_coordinate_space.hpp
  glm/gtx/hash.inl
  glm/gtx/normalize_dot.hpp
  glm/gtx/pca.hpp
  glm/gtx/quaternion.hpp
  glm/gtx/scalar_multiplication.hpp
  glm/gtx/vec_swizzle.hpp
  glm/gtx/vector_query.hpp
Labels: documentation

#1113 GCC: Fix noexcept warnings on hash functions
  glm/detail/setup.hpp
  glm/detail/type_mat2x2.hpp
  glm/detail/type_mat2x2.inl
  glm/detail/type_mat2x3.hpp
  glm/detail/type_mat2x3.inl
  glm/detail/type_mat2x4.hpp
  glm/detail/type_mat2x4.inl
  glm/detail/type_mat3x2.hpp
  glm/detail/type_mat3x2.inl
  glm/detail/type_mat3x3.hpp
  glm/detail/type_mat3x3.inl
  glm/detail/type_mat3x4.hpp
  glm/detail/type_mat3x4.inl
  glm/detail/type_mat4x2.hpp
  glm/detail/type_mat4x2.inl
  glm/detail/type_mat4x3.hpp
  glm/detail/type_mat4x3.inl
  glm/detail/type_mat4x4.hpp
  glm/detail/type_mat4x4.inl
  glm/gtx/hash.hpp
  glm/gtx/hash.inl
  test/gtx/CMakeLists.txt
  test/gtx/gtx_hash.cpp
Labels: enhancement

#1120 docs(manual): some markdown fixes
  manual.md
Labels: documentation

#1112 Fixed a typo in io.hpp.
  glm/gtx/io.hpp
Labels: bug

#1116 GLM_EXT_matrix_common : add glm::mat<> support to glm::abs()
  glm/ext/_matrix_vectorize.hpp
  glm/ext/matrix_common.hpp
  glm/ext/matrix_common.inl
  test/ext/ext_matrix_common.cpp
Labels: extension, feature

#1109 Documentation: spelling, grammar, and clarity
  doc/api/a00242.html
  glm/exponential.hpp
  readme.md
Labels: documentation

#1086 Fixed use of undeclared identifier 'vdivq_f32' while compile for ARMv7
  glm/detail/type_vec4_simd.inl
Labels: enhancement

#1122 Fix GLM_EXT_matrix_common : row to column-major
  glm/ext/_matrix_vectorize.hpp
  test/ext/ext_matrix_common.cpp
Labels: bug
