Repository g-truc/glm, pull requests merged in 2023-12, with the labels that each got.

#1174 Fix doc typo
  readme.md
Labels: documentation

#1170 Fix intersect ray triangle #1158
  glm/gtx/intersect.inl
Labels: bug, P2: extension

#1173 cuda: Fix GTX_vec_swizzle
  glm/gtx/vec_swizzle.hpp
Labels: bug, CC: cuda

#1172 Fix bitCount test version
  test/core/core_func_integer.cpp
Labels: bug, P1: core

#1176 Fix GTC_matrix_transform test for C++98
  test/gtc/gtc_matrix_transform.cpp
Labels: bug, test, P0: Must Fix

#1175 Fix lib build dependent of test build
  glm/CMakeLists.txt
  test/CMakeLists.txt
Labels: cmake

#1045 GLM_EXT_vector_integer mix tests based on GLM_FORCE_UNRESTRICTED_GENTYPE
  test/ext/ext_vector_integer.cpp
Labels: test

#1196 Add missing headers in ext.hpp
  glm/ext.hpp
Labels: bug, core, OS: Platform independent

#1199 Test multiple platforms to test multiple compiler versions
  .github/workflows/ci.yml
  glm/simd/platform.h
  test/CMakeLists.txt
  test/core/core_setup_message.cpp
  test/perf/perf_matrix_inverse.cpp
Labels: enhancement, c.i.

#1202 Fix GLM_GTX_hash
  glm/ext.hpp
  glm/gtx/hash.hpp
  glm/gtx/hash.inl
  test/gtx/gtx_hash.cpp
  test/gtx/gtx_quaternion.cpp
Labels: bug, extension, OS: Platform independent

#1204 Fix quat packing XYZW usage
  glm/detail/type_quat.hpp
  glm/detail/type_quat.inl
  glm/detail/type_quat_simd.inl
  glm/gtx/matrix_decompose.inl
Labels: bug, extension, OS: Platform independent

#1206 Fix quat angle documentation #820
  glm/ext/quaternion_trigonometric.hpp
Labels: extension, documentation, OS: Platform independent

#1207 Enable cuda swizzle
  glm/detail/_swizzle_func.hpp
Labels: enhancement, CC: cuda, core, OS: Platform independent

#1208 Add C++ 20 Modules
  glm/glm.cppm
  glm/gtx/number_precision.hpp
Labels: feature, OS: Platform independent
