Repository g-truc/glm, pull requests merged in 2024-12, with the labels that each got.

#1318 Remove Android-specific detection of GLM_HAS_CXX11_STL
  glm/detail/setup.hpp
Labels: enhancement, OS: android

#1330 Specify CMake policy range to avoid deprecation warning
  CMakeLists.txt
Labels: OS: Platform independent

#1328 Fix module interface missing some gtx quaternion functions
  glm/glm.cppm
Labels: bug
