Repository g-truc/glm, pull requests merged in 2025-01, with the labels that each got.

#1312 fix levels() calculation for scalars
  glm/gtx/texture.inl
Labels: bug, extension, OS: Platform independent

#1317 Fixed infinitePerspective declarations and definitions
  glm/ext/matrix_clip_space.hpp
  glm/ext/matrix_clip_space.inl
Labels: enhancement, extension, OS: Platform independent

#1315 Fix a wrong macro for tdualquat ctor
  glm/gtx/dual_quaternion.hpp
Labels: bug, OS: Platform independent

#1311 Fix build error with GLM_FORCE_INTRINSICS and NEON
  glm/detail/func_common_simd.inl
  glm/detail/type_vec_simd.inl
  test/core/CMakeLists.txt
  test/core/core_force_intrinsics.cpp
Labels: bug, OS: Platform independent, c.i.

#1339 Rebase 1.0.2
  .github/workflows/ci.yml
  CMakeLists.txt
  glm/detail/func_common_simd.inl
  glm/detail/qualifier.hpp
  glm/gtx/dual_quaternion.hpp
  glm/gtx/pca.inl
  readme.md
  test/core/core_force_intrinsics.cpp
  test/core/core_type_aligned.cpp
  test/gtc/gtc_type_aligned.cpp
  test/gtx/gtx_intersect.cpp
Labels: OS: Platform independent
